global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'llm-app'
    static_configs:
      - targets: ['llm-app:8000']
    scrape_interval: 5s
    metrics_path: /metrics
